# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

source $ZSH/oh-my-zsh.sh

# Set name of the theme to load
ZSH_THEME="robbyrussell"

# Homebrew configuration
eval "$(/opt/homebrew/bin/brew shellenv)"

# Ruby configuration
export LDFLAGS="-L$(brew --prefix libyaml)/lib"
export CPPFLAGS="-I$(brew --prefix libyaml)/include"
export RUBY_YJIT_ENABLE=1
export RUBY_CONFIGURE_OPTS=--enable-yjit

# Development environment setup
# Initialize mise (previously rtx) for version management
eval "$(mise activate zsh)"

eval "$(fzf --zsh)"

# PostgreSQL path configuration
export PATH="/opt/homebrew/opt/postgresql@17/bin:$PATH"

export PGGSSENCMODE="disable"

export PATH="$HOME/.local/bin:$PATH"
